# -*- coding: utf-8 -*-
"""Geo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuLljnun5musJoh2osONyUAohWXo2kVf
"""

import geopandas as gpd

def load_gminy(path: str):
    gdf = gpd.read_file(path)
    gdf["terc"] = gdf["terc"].astype(str)
    return gdf