# -*- coding: utf-8 -*-
"""Wynagrodzenia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuLljnun5musJoh2osONyUAohWXo2kVf
"""

import pandas as pd

def load_Wynagrodzenia(path: str):
    return pd.read_excel(
        path,
        dtype={"Kod": str}
    )