# -*- coding: utf-8 -*-
"""mapa_mediana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuLljnun5musJoh2osONyUAohWXo2kVf
"""

import folium
from streamlit_folium import st_folium

def mediana_gminy(gdf, mediana: str):
    m = folium.Map(
        location=[52.0, 19.0],
        zoom_start=6,
        tiles="cartodbpositron"
    )

    folium.Choropleth(
        geo_data=gdf,
        data=gdf,
        columns=["terc", mediana],
        key_on="feature.properties.terc",
        fill_color="YlGnBu",
        fill_opacity=0.8,
        line_opacity=0.2,
        nan_fill_color="lightgray",
        legend_name=mediana
    ).add_to(m)

    return st_folium(m, height=600, use_container_width=True)

